<?php $install_config = array (
  'db_type' => 'mysqli_innodb',
  'db_port' => '3306',
  'db_hostname' => 'localhost',
  'db_userid' => 'xpressengine',
  'db_password' => 'xpressengine',
  'db_database' => 'xpressengine',
  'db_table_prefix' => 'xe_auto',
  'db_charset' => 'utf8',
  'use_rewrite' => 'Y',
  'time_zone' => '0900',
  'email_address' => 'admin@admin.net',
  'password' => 'admin1!2@',
  'password2' => 'admin1!2@',
  'nick_name' => 'admin',
  'user_id' => 'admin',
  'lang_type' => 'ko',
);